"use client";
import { useState } from "react";

type Place = { id: string; displayName?: { text: string }; formattedAddress?: string; websiteUri?: string; primaryType?: string };
export function LeadsStudio() {
  const [places, setPlaces] = useState<Place[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function discover(data: FormData) { setBusy(true); setMessage(""); const response = await fetch("/api/leads/discover", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(data)) }); const json = await response.json(); setBusy(false); if (!response.ok) return setMessage(json.error || "Zoeken mislukt."); setPlaces(json.places || []); }
  return <><form action={discover} className="lead-form studio-search"><label>Branche<input name="sector" required placeholder="bijvoorbeeld kapper" /></label><label>Plaats of regio<input name="location" required placeholder="bijvoorbeeld Breda" /></label><button className="button-primary" disabled={busy}>{busy ? "Zoeken..." : "Vind bedrijven via Google Places"}</button>{message && <p className="form-error">{message}</p>}</form><div className="lead-table"><div className="lead-table-head"><span>Bedrijf</span><span>Website</span><span>Adres</span><span>Belroute</span></div>{places.map((place) => <article key={place.id}><span><b>{place.displayName?.text}</b><small>Place ID: {place.id}</small></span><span>{place.websiteUri ? <a href={place.websiteUri} target="_blank">Website openen</a> : "Geen website vermeld"}</span><span>{place.formattedAddress}</span><span><b className="status-hold">Eerst rechtsvorm controleren</b><small>Eenmanszaak/VOF alleen bellen met aantoonbare opt-in.</small></span></article>)}</div><p className="form-note">Google Places-resultaten zijn een werklijst, geen beltoestemming. Bewaar duurzaam alleen het Place ID en je eigen audits/notities; controleer rechtsvorm en bestaande klantrelatie vóór telefonisch contact.</p></>;
}
